### ISSUE TITLE
Keep/drop dice and other RP-related dice modifiers

### ISSUE THREAD

**Issue by SorteKanin** [markbrockettrobson/python_dice#30]
Hey, really cool dice roller. Seems really useful.

I thought it would be cool if there were a few more common functions used in many role-playing systems. Specifically, keeping or dropping dice would be a very useful feature for rolling stats in games like Pathfinder and Dungeons and Dragons.

Syntax for keep/drop dice has already been practically standardized by Roll20, which can be seen here: https://wiki.roll20.net/Dice_Reference

There's also lots of other options for dice modifiers which could be useful for this library. Though I don't know how the statistical output would handle things like exploding dice, since such rolls could in theory go to infinity.

If you could add any of the functionality from roll20, that'd be really great. Otherwise, perhaps you could give me some pointers as to how I might implement it myself?

**Comment by markbrockettrobson** [comment]
Thanks for the feedback I will look into adding them.

**Comment by markbrockettrobson** [comment]
keep and drop added in version 1.0.0

**Comment by markbrockettrobson** [comment]
Custom dice and fate dice added in version 1.1.0
